export const  listOfCities = [
    'Accra',
    'Addis Ababa',
    'Amman',
    'Amsterdam',
    'Ankara',
    'Astana',
    'Baghdad',
    'Baku',
    'Bangkok',
    'Banjul',
    'Beijing',
    'Beirut',
    'Belgrade',
    'Berlin',
    'Bern',
    'Bishkek',
    'Bratislava',
    'Brazzaville',
    'Bridgetown',
    'Brussels',
    'Bucharest',
    'Budapest',
    'Buenos Aires',
    'Canberra',
    'Copenhagen',
    'Dakar',
    'Damascus',
    'Dublin',
    'Dushanbe',
    'Georgetown',
    'Gibraltar',
    'Guatemala',
    'Hamilton',
    'Hanoi',
    'Harare',
    'Havana',
    'Helsinki',
    'Honiara',
    'Islamabad',
    'Jakarta',
    'Jamestown',
    'Jerusalem',
    'Kabul',
    'Kampala',
    'Kathmandu',
    'Kiev',
    'Kingston',
    'Kingstown',
    'Kinshasa',
    'Libreville',
    'Lilongwe',
    'Lisbon',
    'Ljubljana',
    'London',
    'Luxembourg',
    'Mexico',
    'Minsk',
    'Monaco',
    'Moscow',
    'New Delhi',
    'Oranjestad',
    'Oslo',
    'Ottawa',
    'Ouagadougou',
    'Pago Pago',
    'Palikir',
    'Panama City',
    'Paramaribo',
    'Paris',
    'Cape Town',
    'Reykjavík',
    'Riga',
    'Rome',
    'Roseau',
    'Saipan',
    'San Marino',
  '  San Salvador',
    'Santiago',
'    Seoul',
    'Singapore',
    'Sofia',
    'Stanley',
    'Stockholm',
    'Tallinn',
    'Tashkent',
    'Tbilisi',
    'Tehran',
    'Tokyo',
    'Tripoli',
    'Tskhinvali',
    'Tunis',
    'Ulan Bator',
    'Valletta',
    'Vatican',
    'Victoria',
    'Vienna',
    'Vientiane',
    'Vilnius',
    'Warsaw',
    'Wellington',
    'West Island',
    'Willemstad',
    'Abidjan',
    'Yerevan',
    'Zagreb'
]
